<?php 

/*
Plugin Name: Azkaar English
Plugin URI: http://www.wordpress.org/plugins/azkaar-english
Description: This plugin displays a random supplication (Arabic + Translation) from Qur'an / Sunnah.
Version: 1.2
Author: Azkaar Developers
Author URI: http://www.azkaar.com/feedback
License: GPL2
*/


// WIDGET CSS
function azkaar_scripts() {
	wp_enqueue_style( 'azkaar-style', plugins_url( '/azkaar-styles.css', __FILE__ ), false, '1.0', 'all' );
}
add_action( 'wp_enqueue_scripts', 'azkaar_scripts' );


class AzkaarEnglishPluginWidget extends WP_Widget {

    // constructor
    function AzkaarEnglishPluginWidget() {
        parent::__construct( false, 'Azkaar English' );
    }
	

	// widget form creation
	function form($instance) {

		// Check values
		if( $instance) {
			 $title = esc_attr($instance['title']);
		} else {
			 $title = '';
		}
		?>

		<div>
		<b><label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title', 'AzkaarEnglishPluginWidget'); ?></label></b>
		<input class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" type="text" value="<?php echo $title; ?>" />
		</div>

		<?php
	}
 
	// update widget
	function update($new_instance, $old_instance) {
		$instance = $old_instance;
		// Fields
		$instance['title'] = strip_tags($new_instance['title']);
		return $instance;
	} 

		
	// display widget
	function widget($args, $instance) {
		
		extract( $args );
		// these are the widget options
		// $title = apply_filters('widget_title', $instance['title']);
		// if ( $title ) $widget_data .= $before_title . $title . $after_title;
			
		

				
		$azkaar_array = array(
			"Starting Ablution by Saying &#039;Bismillah&#039;|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/012.gif'></div>|<div class='dua_trans'>In the name of Allah.</div>",
			"Saying &#039;Shahadah&#039; Upon Completing Ablution|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/013.gif'></div>|<div class='dua_trans'>I bear witness that none has the right to be worshiped except Allah, alone, without partner, and I bear witness that Muhammad is His slave and Messenger.</div>",
			"Dua to Say After Ablution: O Allah, I Seek Your Forgiveness|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/015.gif'></div>|<div class='dua_trans'>How perfect You are O Allah, and I praise You, I bear witness that none has the right to be worshipped except You, I seek Your forgiveness and turn in repentance to You.</div>",
			"Dua to Say After Ablution: O Allah, Make Me Remain Clean and Pure|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/014.gif'></div>|<div class='dua_trans'>O Allah, make me of those who return to You often in repentance and make me of those who remain clean and pure.</div>",
			"Answering Muadhin&#039;s Call|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/022.gif'></div>|<div>(i) One repeats just as the muadhdhin (مؤذن) says:</div><div class='dua_trans'>'Come to prayer, come to success'.</div><div>(ii) Or one could say:</div><div class='dua_trans'>There is no might nor power except with Allah.</div>",
			"Dua to Say During Adhan|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/023.gif'></div>|<div>Immediately following the declaration of faith called by the muadhdhin (مؤذن), one says:</div><div class='dua_trans'>And I too bear witness that none has the right to be worshipped except Allah, alone, without partner, and that Muhammad is His slave and Messenger. I am pleased with Allah as a Lord, and Muhammad as a Messenger and Islaam as a religion.</div>",
			"Dua to Say After Adhan: O Allah, Owner of This Perfect Call|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/025.gif'></div>|<div>One should then send prayers on the Prophet (S) after answering the call of the Muadhdhin (مؤذن): </div><div class='dua_trans'>‘O Allah, Owner of this perfect call and Owner of this prayer to be performed, bestow upon Muhammad al-waseelah (الوسیلۃ) and al-fadeelah (الفضیلۃ) and send him upon a praised platform which You have promised him. Verily, You never fail in Your promise.’</div><div>One should also supplicate for himself during the time between the adhaan (أذان) and the iqaamah (اقامۃ) as supplication at such time is not rejected.</div>",
			"Dua to Say When Entering the Mosque|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/020.gif'></div>|<div class='dua_trans'>‘I take refuge with Allah, The Supreme and with His Noble Face, and His eternal authority from the accursed devil. In the name of Allah, and prayers and peace be upon the Messenger of Allah. O Allah, open the gates of Your mercy for me.’</div>",
			"Dua to Say After First Takbir in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/028.gif'></div>|<div class='dua_trans'>‘How perfect You are O Allah, and I praise You. Blessed be Your name, and lofty is Your position and none has the right to be worshipped except You.’</div>",
			"Dua to Say While Bowing in Salah: How Perfect My Lord is, The Supreme|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/033.gif'></div>|<div>Three Times</div><div class='dua_trans'>‘How perfect my Lord is, The Supreme.’</div>",
			"Dua to Say While Bowing in Salah: Allah, Lord of the Angels and the Ruh|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/035.gif'></div>|<div class='dua_trans'>‘Perfect and Holy (He is), Lord of the angels and the Ruh (i.e. Jibraa’eel).’</div>",
			"Dua to Say While Bowing in Salah: Allah, the Possessor of Total Power|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/037.gif'></div>|<div class='dua_trans'>‘How perfect He is, The Possessor of total power, sovereignty, magnificence and grandeur.’</div>",
			"Dua to Say While Bowing in Salah: O Allah, Forgive Me|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/034.gif'></div>|<div class='dua_trans'>‘How perfect You are O Allah, our Lord and I praise You. O Allah, forgive me.’</div>",
			"Dua to Say While Bowing in Salah: O Allah, Unto You I Have Bowed|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/036.gif'></div>|<div class='dua_trans'>O Allah, unto You I have bowed, and in You I have believed, and to You I have submitted. My hearing, sight, mind, bones, tendons and what my feet carry are humbled before You.’</div>",
			"Dua to Say While Rising from Bowing: May Allah Answer He Who Praises Him|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/038.gif'></div>|<div class='dua_trans'>‘May Allah answer he who praises Him.’</div>",
			"Dua to Say When Rising from Bowing in Salah: Our Lord, for You is All Praise|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/039.gif'></div>|<div class='dua_trans'>‘Our Lord, for You is all praise, an abundant beautiful blessed praise.’ </div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/041.gif'></div>|<div>Three times:</div><div class='dua_trans'>‘How perfect my Lord is, The Most High.’</div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/045.gif'></div>|<div class='dua_trans'>‘How perfect He is, The Possessor of total power, sovereignty, magnificence and grandeur.’</div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/044.gif'></div>|<div class='dua_trans'>‘O Allah, unto You I have prostrated and in You I have believed, and unto You I have submitted. My face has prostrated before He Who created it and fashioned it, and brought forth its faculties of hearing and seeing. Blessed is Allah, the Best of creators.’ </div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/046.gif'></div>|<div class='dua_trans'>‘O Allah, forgive me all of my sins, the smaal and great of them, the first and last of them, and the seen and hidden of them.’</div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/047.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge within Your pleasure from Your displeasure and within Your pardon from Your punishment, and I take refuge in You from You. I cannot enumerate Your praise. You are as You have praised Yourself.’</div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/042.gif'></div>|<div class='dua_trans'>‘How perfect You are O Allah, our Lord, and I praise You. O Allah, forgive me.’</div>",
			"Dua to Say While Prostrating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/043.gif'></div>|<div class='dua_trans'>‘Perfect and Holy (He is), Lord of the angels and the Ruuh (i.e. Jibraa’eel).’</div>",
			"Dua to Say Between Two Prostrations|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/049.gif'></div>|<div class='dua_trans'>‘O Allah, forgive me, have mercy upon me, guide me, enrich me, give me health, grant me sustenance and raise my rank.’</div>",
			"Dua to Say Between Two Prostrations|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/048.gif'></div>|<div class='dua_trans'>‘O Allah, forgive me, O Allah, forgive me.’</div>",
			"After Adhan Sending Prayer upon the Prophet Muhammad (PBUH)|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/024.gif'></div>|<div class='dua_trans'>‘O Allah, send prayers upon Muhammad and the followers of Muhammad, just as You sent prayers upon Ibraheem and upon the followers of Ibraheem. Verily, You are full of praise and majesty. O Allah, send blessings upon Muhammad and upon the family of Muhammad, just as You sent blessings upon Ibraheem and upon the family of Ibraheem. Verily, You are full of praise and majesty.’ </div>",
			"The Tashahhud in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/052.gif'></div>|<div class='dua_trans'>‘Al-Tahiyyaat is for Allah. All acts of worship and good deeds are for Him. Peace and the mercy and blessings of Allah be upon you O Prophet. Peace be upon us and all of Allah’s righteous servants. I bear witness that none has the right to be worshipped except of Allah and I bear witness that Muhammad is His slave and Messenger.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/059.gif'></div>|<div class='dua_trans'>‘O Allah, help me to remember You, to thank You, and to worship You in the best of manners.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/061.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You to grant me Paradise and I take refuge in You from the Fire.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/055.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge in You from the punishment of the grave, from the torment of the Fire, from the trials and tribulations of life and death and from the evil affliction of the Al-Maseeh Ad-Dajjaal.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/058.gif'></div>|<div class='dua_trans'>‘O Allah, forgive me for those sins which have come to pass as well as those which shall come to pass, and those I have committed in secret as well as those I have made public, and where I have exceeded all bounds as well as those things about which You are more knowledgeable. You are Al-Muqaddim and Al-Mu’akhhir. None has the right to be worshipped except You.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/057.gif'></div>|<div class='dua_trans'>O Allah, I have indeed oppressed my soul excessively and none can forgive sin except You, so forgive me a forgiveness from Yourself and have mercy upon me. Surely, You are The Most-Forgiving, The Most-Merciful</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/060.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge in You from miserliness and cowardice, I take refuge in You lest I be returned to the worst of lives, and I take refuge in You from the trials and tribulations of this life and the punishment of the grave.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/065.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You, as I bear witness that You are Allah, none has the right to be worshipped except You, The One, As-Samad Who begets not nor was He begotten and there is none like unto Him.’</div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/056.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge in You form the punishment of the grave, and I take refuge in You from the temptation and trial of Al-Maseeh Al-Dajjaal, and I take refuge in You from the trials and tribulations of life and death. O Allah, I take refuge in You from sin and debt.’ </div>",
			"Dua to Say Before Salam in Salah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/063.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You O Allah, as You are-The One, The Only, As-Samad, The One who begets not, nor was He begotten and there isnone like unto Him- that You forgive me my sins for verily You are The Oft-Forgiving, Most-Merciful.’</div>",
			"Saying Astaghfirullah (3 Times) After Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/066.gif'></div>|<div>(1)</div><div class='dua_trans'>‘I ask Allah for forgiveness.’</div><div>(2)</div><div class='dua_trans'>‘O Allah, You are As-Salam and from You is all peace, blessed are You, O Possessor of majesty and honor.’</div>",
			"Saying Subhanallah, Alhamdulillah, Allahu Akbar (33 Times) After Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/069.gif'></div>|<div class='dua_trans'>‘How perfect Allah is, all praise is for Allah, and Allah is the greatest.’ (33 times)</div><div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, and He is over all things omnipotent.’</div>",
			"Reciting &#039;Ayat Al-Kursi&#039; After Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/071.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped but He, the Ever Living, the One Who sustains and protects all that exists. Neither slumber, nor sleep overtake Him. To Him belongs whatever is in the heavens and whatever is on earth. Who is he that can intercede with Him except with His Permission? He knows what happens to them (His creatures) in this world, and what will happen to them in the Hereafter . And they will never compass anything of His Knowledge except that which He wills. His Kursî[] extends over the heavens and the earth, and He feels no fatigue in guarding and preserving them. And He is the Most High, the Most Great‘.</div>",
			"Dua to Say After Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/067.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah, alone without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent. O Allah, none can prevent what You have willed to bestow and none can bestow what You have willed to prevent, and no wealth or majesty can benefit anyone, as from You is all wealth and majesty.’</div>",
			"Dua to Say After Fajr Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/073.gif'></div>|<div>To be said afer giving salam for the fajr prayer:</div><div class='dua_trans'>‘O Allah, I ask You for knowledge which is beneficial and sustenance which is good, and deeds which are acceptable.’</div>",
			"Dua to Say After Fajr and Maghrib Prayers|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/072.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, He gives life and causes death and He is over all things omnipotent.’</div>",
			"Dua of Witr Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/113.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge within Your pleasure from Your displeasure and within Your pardon from Your punishment, and I take refuge in You from You. I cannot enumerate You praise. You are as You have praised Yourself.’</div>",
			"Dua to Say After Witr Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/115.gif'></div>|<div>The Messenger of Allah (PBUH) would recite (the following chapters) during the witr prayer:</div><div>(1)</div><div class='dua_trans'>Surah al-A'laa<br />Surah al-Kaafiruun<br />Surah al-Ikhlaas</div><div>After giving the salam the prophet (PBUH) would supplicate 3 times:</div><div>(2)</div><div class='dua_trans'>‘How perfect The King, The Holy One is.’</div><div>On the 3rd time the prophet (PBUH) would raise his voice, elongate it and add:</div><div>(3)</div><div class='dua_trans'>‘Lord of the angels and the Ruh’ (i.e. Jibraa’eel).</div>",
			"Dua to Say When Leaving the Mosque|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/021.gif'></div>|<div class='dua_trans'>‘In the name of Allah, and prayers and peace be upon the Messenger of Allah. O Allah, I ask You from Your favor. O Allah, guard me from the accursed devil.’</div>",
			"Dua for Prostration of Recitation|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/051.gif'></div>|<div class='dua_trans'>‘O Allah, record for me a reward for this (prostration), and remove from me a sin. Save it for me and accept it from me just as You had accepted it from Your servant Daawud.’</div>",
			"Dua for Prostration of Recitation|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/050.gif'></div>|<div class='dua_trans'>‘My face fell prostrate before He who created it and brought forth its faculties of hearing and seeing by His might and power.<br />So Blessed is Allah, the best of creators.’</div>",
			"Dua to Say Upon Breaking Fast|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/169.gif'></div>|<div>‘Abdullah Ibn ‘Amr Ibn Al-‘Aas related that the Messenger of Allah (S) said: ‘Indeed the fasting person has at the time of breaking fast, a supplication which is not rejected’. Ibn Abee Mulaykah said: ‘I heard ‘Abdullaah Ibn ‘Umar say when he broke fast:</div><div class='dua_trans'>‘O Allah, I ask You by Your mercy which envelops all things, that You forgive me.’</div>",
			"Dua to Say Upon Breaking Fast|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/168.gif'></div>|<div class='dua_trans'>‘The thirst has gone and the veins are quenched, and reward is confirmed, if Allah wills.’</div>",
			"Dua to Say When Breaking Fast in Someone&#039;s Home|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/176.gif'></div>|<div class='dua_trans'>‘May the fasting break their fast in your home, and may the dutiful and pious eat your food, and may the angels send prayers upon you.’</div>",
			"Dua to Say When Get Insulted While Fasting|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/238.gif'></div>|<div class='dua_trans'>‘I am fasting, I am fasting.’</div>",
			"Dua to Say Between the Yemeni Corner and Hajr-e-Aswad|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/220.gif'></div>|<div>The Prophet Muhammad (PBUH) used to say between the Yemeni corner and the black stone:</div><div class='dua_trans'>‘O our Lord, grant us the best in this life and the best in the next life, and protect us from the punishment of the Fire.’ </div>",
			"Dua to Say At Hajr Aswad|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/225.gif'></div>|<div>‘The Prophet (S) circled the Ka’bah on a camel, every time he reached the black stone he would point to it with his staff and say:</div><div class='dua_trans'>‘Allah is the greatest.’</div>",
			"The Best of Dua on the Day of Arafah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/222.gif'></div>|<div>The prophet (PBUH) said: ‘The best of supplications is the supplication on the day of ‘Arafah and the best which I and the Prophets before me have said (is):</div><div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner. To Him belongs all praise and sovereignty and He is over all things omnipotent.’</div>",
			"The Talbiyah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/234.gif'></div>|<div class='dua_trans'>‘Here I am O Allah, (in response to Your call), here I am. Here I am, You have no partner, here I am. Verily all praise, grace and sovereignty belong to You. You have no partner.’</div>",
			"Dua to Say When Throwing Each Pebble at the Jamaraat|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/224.gif'></div>|<div>Every time the Prophet (PBUH) threw a pebble at any of the three jamaraat, he would say:</div><div class='dua_trans'>‘Allah is the greatest.’</div><div>On completion of the first jamarah, the prophet (PBUH) advanced a little, stood facing the qiblah, raised his hands and supplicated. He also did this after the second jamarah but not the third.’</div>",
			"Dua to Say When Slaughtering or Offering a Sacrifice|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/239.gif'></div>|<div class='dua_trans'>‘In the name of Allah, and Allah is the greatest. O Allah, (it is) from You and belongs to You, O Allah, accept this from me.’</div>",
			"Dua to Say When Feeling Doubt in Your Faith|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/127.gif'></div>|<div class='dua_trans'>‘He is The First and The Last, Ath-Thahir and Al-Batin and He knows well all things.’</div>",
			"Dua to Say When Feeling Doubt in Your Faith|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/126.gif'></div>|<div class='dua_trans'>‘I have believed in Allah and His Messengers.’</div>",
			"Dua to Say When Seeing Someone in a Trial|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/184.gif'></div>|<div class='dua_trans'>‘All praise if for Allah Who saved me from that which He tested you with and Who most certainly favored me over much of His creation.’</div>",
			"Dua to Say When Buying an Animal|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/181.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You for the goodness within her and the goodness that you have made her inclined towards, and I take refuge with You from the evil within her and the evil that you have made her inclined towards.’</div><div>And if you buy a camel, then you should take hold of it’s hump and say likewise.</div>",
			"Forbiddance of Ascribing Things to Omens|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/196.gif'></div>|<div class='dua_trans'>‘O Allah, there is no omen but there is reliance on You, there is no good except Your good and none has the right to be worshipped except You.’ </div>",
			"Seeking Refuge with Allah’s Perfect Words|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/082.gif'></div>|<div class='dua_trans'>‘I take refuge in Allah’s perfect words from the evil He has created.’</div><div>(3 times in the evening)</div>",
			"Dua for Protection from Satan All Day and Night|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/092.gif'></div>|<div>The Messenger of Allah (PBUH) said:<br />‘Whoever says (the following) in the morning, has indeed gained the reward of freeing a slave from the children of Ismaa’eel, and ten of his sins are wiped away and he is raised ten degrees, and he has found a safe retreat from the devil until evening. Similarly, if he says it at evening time, he will be protected until the morning.’ :</div><div class='dua_trans'>‘None has the right to be worshiped except Allah alone, without partner, to Him belongs all sovereignty and praise and He is over all things omnipotent.’</div>",
			"Dua to Say After Dismissal of a Sitting|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/187.gif'></div>|<div class='dua_trans'>‘How perfect You are, and I praise you, None has the right to be worshipped except You, I seek Your forgiveness and trun to You in repentance.’</div>",
			"Dua to Say At the End of a Sitting or Gathering|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/186.gif'></div>|<div class='dua_trans'>‘How perfect You are O Allah, and I praise You. I bear witness that none has the right to be worshipped except You. I seek Your forgiveness and turn to You in repentance.’</div>",
			"Returning a Dua of Forgiveness|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/188.gif'></div>|<div>Abdullah ibn Sarjis (RA) said:<br />‘I went to see the Prophet (PBUH) and ate from his food and then said to him:<br />(1)</div><div class='dua_trans'>‘May Allah forgive you, O Messenger of Allah.’</div><div>The prophet (PBUH) replied:<br />(2)</div><div class='dua_trans'>‘And (may Allah forgive) you (too).’</div>",
			"Dua for Seeking Forgiveness and Repentance|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/243.gif'></div>|<div>The prophet (PBUH) said: ‘Whoever says (the following), Allah would forgive him even if he was one who fled during the advance of an army.’</div><div class='dua_trans'>‘I seek Allah’s forgiveness, besides whom, none has the right to be worshiped except He, The Ever Living, The Self-Subsisting and Supporter of all, I turn to Him in repentance.’</div>",
			"Dua to Say at Sitting or Gathering|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/185.gif'></div>|<div>Ibn ‘Umar (RA) said: It would be counted that the Messenger of Allah (PBUH) would say one hundred times at any one sitting before getting up:</div><div class='dua_trans'>‘O my Lord, forgive me and turn towards me (to accept my repentance). Verily You are The Oft-Returning, the Oft-Forgiving.</div>",
			"All Praise is for Allah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/253.gif'></div>|<div>Jabir ibn Abdullah (RA) related that the Messenger of Allah (PBUH) said:</div><div>‘Verily, the best supplication is:</div><div>(1)</div><div class='dua_trans'>‘All praise is for Allah.’</div><div>(2)</div><div>and indeed, the best form of remembrance is:</div><div class='dua_trans'>‘None has the right to be worshiped except Allah.’</div>",
			"Allah is the Greatest|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/250.gif'></div>|<div>‘The most beloved words to Allah are (the following) four, it does not matter which of them you start with.’</div><div class='dua_trans'>‘How perfect Allah is, all praise if for Allah. None has the right to be worshipped except Allah and Allah is the greatest.’</div>",
			"How Perfect Allah is, and All Praise is For Allah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/254.gif'></div>|<div class='dua_trans'>‘How perfect Allah is, and all praise is for Allah. None has the right to be worshipped except Allah, and Allah is the greatest. There is no might nor power except with Allah.’</div>",
			"The Words Which are Light on the Tongue and Heavy on the Scale|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/249.gif'></div>|<div>Abu Hurayrah (RA) reported that the Messenger of Allah (PBUH) said:<br />‘(There are) Two words, (which are) light on the tongue, heavy on the Scale and beloved to The Most Gracious':</div><div class='dua_trans'>‘How perfect Allah is and I praise Him. How perfect Allah is, The Supreme.’</div>",
			"Dua to Say When Feeling Sorrow|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/117.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge in You from anxiety and sorrow, weakness and laziness, miserliness and cowardice, the burden of debts and from being over powered by men.’</div>",
			"Dua for the Fear of Shirk in Faith|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/194.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge in You lest I should commit shirk with You knowingly and I seek Your forgiveness for what I do unknowingly.’</div>",
			"Dua to Say When Afflicted by a Calamity|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/146.gif'></div>|<div class='dua_trans'>‘To Allah we belong and unto Him is our return. O Allah, recompense me for my affliction and replace it for me with something better.’</div>",
			"Dua to Say When Feeling Sorrow|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/121.gif'></div>|<div class='dua_trans'>‘Allah, Allah is my Lord, I do not associate anything with Him.’</div>",
			"Dua to Say When Feeling Sorrow|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/120.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except You. How perfect Your are, verily I was among the wrong-doers.’</div>",
			"Dua to Say When Feeling Sorrow|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/119.gif'></div>|<div class='dua_trans'>‘O Allah, it is Your mercy that I hope for, so do not leave me in charge of my affairs even for a blink of an eye and rectify for me all of my affairs. None has the right to be worshipped except You.’</div>",
			"Dua to Say When Feeling Sorrow|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/118.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah Forbearing. None has the right to be worshipped except Allah, Lord of the magnificent throne. None has the right to be worshipped except Allah, Lord of the heavens, Lord of the Earth and Lord of the noble throne.’ </div>",
			"Dua Made Against an Enemy|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/226.gif'></div>|<div class='dua_trans'>‘O Allah, Revealer of the Book, Swift at reckoning, defeat the confederates. O Allah, defeat them and convulse them.’</div>",
			"Dua to Say upon Encountering an Enemy|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/124.gif'></div>|<div class='dua_trans'>‘Allah is sufficient for us, and how fine a trustee (He is).’</div>",
			"Dua to Say upon Encountering an Enemy|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/123.gif'></div>|<div class='dua_trans'>‘O Allah, You are my supporter and You are my helper, by You I move and by You I attack and by You I battle.’</div>",
			"Dua to Say upon Encountering an Enemy|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/122.gif'></div>|<div class='dua_trans'>‘O Allah, we place You before them and we take refuge in You from their evil.’</div>",
			"Dua to Say upon Encountering an Enemy|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/109.gif'></div>|<div class='dua_trans'>‘I take refuge in the perfect words of Allah from His anger and punishment and from the evil of His servants, and from the madness and appearance of devils.’</div>",
			"Dua to Say When Feeling Pain Somewhere in the Body|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/231.gif'></div>|<div>Place your hand at the place of the pain and say 3 times:</div><div>(1)</div><div class='dua_trans'>‘In the name of Allah’.</div><div>Then supplicate 7 times:</div><div>(2)</div><div class='dua_trans'>‘I take refuge with Allah and within His omnipotence from the evil that I feel and am wary of.’</div>",
			"Dua to Say When in Fear of People|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/227.gif'></div>|<div class='dua_trans'>‘O Allah, protect me from them with what You choose.’</div>",
			"Dua for a Mishap|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/137.gif'></div>|<div>Indeed Allah rebukes due to negligence and slackness, but take to determination and caution, and if a matter should overtake you then say:</div><div class='dua_trans'>‘Allah is sufficient for me, and how fine a trustee (He is).’</div>",
			"Dua for a Mishap|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/136.gif'></div>|<div>‘The strong believer is better and more beloved to Allah, than the weak believer and there is goodness in both. Strive for that which will benefit you, seek help from Allah and do not despair. If a mishap should happen to befall you then do not say ‘ If only I had acted….such and such would have happened’. Rather say:</div><div class='dua_trans'>‘Allah has decreed and what He wills, He does’.</div><div>… for verify ‘If’ lets in the work of the devil.’</div>",
			"Dua to Say When Startled or Shocked|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/235.gif'></div>|<div class='dua_trans'>‘None has the right to be worshiped except Allah.’</div>",
			"Dua to Say When Amazed or Delighted|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/228.gif'></div>|<div class='dua_trans'>‘How perfect Allah is.’</div>",
			"Dua to Say When Amazed or Delighted|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/229.gif'></div>|<div class='dua_trans'>‘Allah is the greatest.’</div>",
			"Allah is Sufficient for Me, Upon Him I Rely|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/081.gif'></div>|<div class='dua_trans'>‘Allah is Sufficient for me, none has the right to be worshipped except Him, upon Him I rely and He is Lord of the exalted throne.’</div><div>(7 times morning and evening).</div>",
			"Dua to Say When the Mounted Animal (or Mean of Transportation) Stumbles|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/201.gif'></div>|<div class='dua_trans'>‘In the name of Allah.’</div>",
			"How Perfect Allah is and I Praise Him|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/088.gif'></div>|<div class='dua_trans'>‘How perfect Allah is and I praise Him.’</div><div>(100 times)</div></tr>",
			"I am Pleased with Allah as a Lord|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/086.gif'></div>|<div class='dua_trans'>‘I am pleased with Allah as a Lord, and Islam as a religion and Muhammad as a Prophet.’</div><div>(3 times)</div>",
			"I Praise Allah by the Number of His Creation|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/087.gif'></div>|<div class='dua_trans'>‘How perfect Allah is and I praise Him by the number of His creation and His pleasure, and by the weight of His throne, and the ink of His words.’</div><div>(3 times)</div>",
			"In the name of Allah, He is the All-Seeing, the All-Knowing|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/085.gif'></div>|<div class='dua_trans'>‘In the name of Allah with those name nothing is harmed on earth nor in the heavens and He is The All-Seeing, The All-Knowing.’</div><div>(3 times)</div>",
			"None Has the Right to be Worshiped Except Allah|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/090.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise, and He is over all things omnipotent.’</div><div>(100 times every day)</div>",
			"O Allah, by Your Permission We Live and Die|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/076.gif'></div>|<div>(1) In the morning:</div><div class='dua_trans'>‘O Allah, by your leave we have reached the morning and by Your leave we have reached the evening, by Your leave we live and die and unto You is our resurrection.’</div><div>(2) In the evening:</div><div class='dua_trans'>‘O Allah, by Your leave we have reached the evening and by Your leave we have reached the morning, by Your leave we live and die and unto You is our return.’</div>",
			"O Allah, Give Me Health and Grant Me Sustenance|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/252.gif'></div>|<div>Tariq Al-Ashja’i (RA) said:<br />‘When someone would embrace Islam, the Prophet (PBUH) would teach him how to perform prayer and then order him to supplicate with the following words:</div><div class='dua_trans'>‘O Allah, forgive me, have mercy upon me, guide me, give me health and grant me sustenance.’</div>",
			"O Allah, I Take Refuge in You from the Evil of This Day|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/091.gif'></div>|<div class='dua_trans'>‘We have reached the morning and at this very time all sovereignty belongs to Allah, Lord of the worlds. O Allah, I as you for the good of this day, its triumphs and its guidance, and I take refuge in You from the evil of this day and the evil that follows it.’</div><div>And likewise in the evening, starting as:<br />‘Amsyna wa Amsal Mulku Lillah...’</div>",
			"O Allah, I Take Refuge with You from Disbelief and Poverty|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/080.gif'></div>|<div>(1) Three times</div><div class='dua_trans'>‘O Allah, grant my body health, O Allah, grant my hearing health, O Allah, grant my sight health. None has the right to be worshipped except You.’</div><div>(2) Three times</div><div class='dua_trans'>‘O Allah, I take refuge with You from disbelief and poverty, and I take refuge with You from the punishment of the grave. None has the right to be worshipped except You.’</div>",
			"O Allah, What Blessing I Have Risen Upon, is from You Alone|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/079.gif'></div>|<div class='dua_trans'>‘O Allah, what blessing I or any of Your creation have risen upon, is from You alone, without partner, so for You is all praise and unto You all thanks.’</div><div>Whoever says this in the morning has indeed offered his day’s thanks and whoever says this in the evening has indeed offered his night’s thanks.</div>",
			"O Allah, You are My Lord, You Created Me and I am Your Servant|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/077.gif'></div>|<div class='dua_trans'>‘O Allah, You are my Lord, none has the right to be worshipped except You, You created me and I am You servant and I abide to Your covenant and promise as best I can, I take refuge in You from the evil of which I committed. I acknowledge Your favour upon me and I acknowledge my sin, so forgive me, for verily none can forgive sin except You.’</div>",
			"Remembrance While Ascending or Descending|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/205.gif'></div>|<div>Jabir (RA) said: While ascending, we would say:</div><div>(1)</div><div class='dua_trans'>‘Allah is the greatest.’</div><div>And when descending, we would say:</div><div>(2)</div><div class='dua_trans'>‘How perfect Allah is.’</div>",
			"Dua to Say When Entering the Market|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/200.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner, to Him belongs all sovereignty and praise. He gives life and causes death, and He is living and does not die. In His hand is all good and He is over all things, omnipotent.’</div>",
			"Dua to Say for One Who Does You a Favor|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/189.gif'></div>|<div>‘If someone does you a favor and you say (the following) then you have indeed excelled in praising him.’:</div><div class='dua_trans'>‘May Allah reward you with goodness.’</div>",
			"Dua for One Who Pronounces His Love for You, for Allah&#039;s Sake|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/191.gif'></div>|<div class='dua_trans'>‘May He, for whom you have loved me, love you.’</div>",
			"Dua to Say upon Sneezing|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/179.gif'></div>|<div>‘When one of you sneezes he should say:</div><div>(1)</div><div class='dua_trans'>‘All praise is for Allah.’</div><div>and his brother or companion should say to him:</div><div>(2)</div><div class='dua_trans'>‘May Allah have mercy upon you.’</div><div>and he (the one who sneezed) replies back to him:</div><div>(3)</div><div class='dua_trans'>‘May Allah guide you and rectify your condition.’</div>",
			"Dua to Say for One You Have Insulted|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/218.gif'></div>|<div class='dua_trans'>‘O Allah, to any believer whom I have insulted, let that be cause to draw him near to You on the Day of Resurrection.’</div>",
			"Dua to Say When a Non-Believer Sneezes|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/236.gif'></div>|<div class='dua_trans'>‘May Allah guide you an rectify your condition.’</div>",
			"Dua to Say When Get Insulted While Fasting|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/238.gif'></div>|<div class='dua_trans'>‘I am fasting, I am fasting.’</div>",
			"Dua said to the Debtor When His Debt is Settled|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/193.gif'></div>|<div class='dua_trans'>‘May Allah bless for you, your family and wealth. Surely commendation and payment are the reward for a loan.’</div>",
			"Dua to Say When Settling a Debt|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/128.gif'></div>|<div class='dua_trans'>‘O Allah, make what is lawful enough for me, as opposed to what is unlawful, and spare me by Your grace, of need of others.’</div>",
			"Dua to Say When Entering Your Home|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/018.gif'></div>|<div class='dua_trans'>‘In the name of Allaah we enter and in the name of Allaah we leave, and upon our Lord we place our trust.’</div>",
			"Dua to Say When Leaving Your Home|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/017.gif'></div>|<div class='dua_trans'>‘O Allah, I take refuge with You lest I should stray or be led astray, or slip or be tripped, or oppress or be oppressed, or behave foolishly or be treated foolishly.’</div>",
			"Dua to Say When Leaving Your Home|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/016.gif'></div>|<div class='dua_trans'>‘In the name of Allah, I place my trust in Allah, and there is no might nor power except with Allah.’</div>",
			"Dua to Say for the Newlywed Person|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/180.gif'></div>|<div class='dua_trans'>‘May Allah bless for you (your spouse) and bless you, and may He unite both of you in goodness.’</div>",
			"Dua to Say Before Sexual Intercourse|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/182.gif'></div>|<div class='dua_trans'>‘In the name of Allah. O Allah, keep the devil away from us and keep the devil away form what you have blessed us with.’</div>",
			"Dua for Placing Children under Allah&#039;s Protection|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/138.gif'></div>|<div>Ibn ‘Abaas related that the Messenger of Allah (S) used to commend Al-Hasan and Al-Husayn to Allah’s protection, saying:</div><div class='dua_trans'>‘I commend you two to the protection of Allah’s perfect words from every devil, vermin, and every evil eye.’</div>",
			"Groom&#039;s Dua on Wedding Night|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/181.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You for the goodness within her and the goodness that you have made her inclined towards, and I take refuge with You from the evil within her and the evil that you have made her inclined towards.’</div>",
			"Dua to Say Before Undressing|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/009.gif'></div>|<div class='dua_trans'>‘In the name of Allah.‘</div>",
			"Dua for Someone Wearing a New Garment|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/008.gif'></div>|<div class='dua_trans'>‘Wear a new, live commendably and die a shaheed.‘</div>",
			"Dua for Someone Wearing a New Garment|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/007.gif'></div>|<div class='dua_trans'>‘May you wear it out and Allah replace it (with another).‘</div>",
			"Dua to Say When Wearing a New Garment|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/006.gif'></div>|<div class='dua_trans'>‘O Allah, for You is all praise, You have clothed me with it (i.e. the garment), I ask You for the good of it and the good for which it was made, and I seek refuge with You from the evil of it and the evil for which it was made.‘</div>",
			"Dua to Say When Wearing a Garment|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/005.gif'></div>|<div class='dua_trans'>‘All Praise is for Allah who has clothed me with this garment and provided it for me, with no power nor might from myself.‘</div>",
			"Dua to Say When Feeling Angry|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/183.gif'></div>|<div class='dua_trans'>‘I take refuge with Allah from the accursed devil.’</div>",
			"Dua of the Guest for the Host|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/174.gif'></div>|<div class='dua_trans'>‘O Allah, bless for them, that which You have provided them, forgive them and have mercy upon them.’</div>",
			"Dua to Say Before Eating|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/170.gif'></div>|<div>‘When you are about to eat, you should say:</div><div>(1)</div><div class='dua_trans'>‘In the Name of Allah.’</div><div>And if you forget to say it before starting, then you should say (when you remember):</div><div>(2)</div><div class='dua_trans'>‘In the Name of Allah in it’s beginning and end.’</div>",
			"Dua to Say Before Eating Meal or Drinking Milk|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/171.gif'></div>|<div>‘Whomever Allah feeds, should say:</div><div>(1)</div><div class='dua_trans'>‘O Allah, bless it for us and feed us better than it.’</div><div>And whomever Allah gives milk to drink, should say:</div><div>(2)</div><div class='dua_trans'>‘O Allah, bless it for us and give us more of it.’</div>",
			"Dua for the One Offering Food or Drink|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/175.gif'></div>|<div class='dua_trans'>‘O Allah, feed him who fed me, and provide with drink him who provided me with drink.’</div>",
			"Dua to Say upon Completing the Meal|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/173.gif'></div>|<div class='dua_trans'>‘Allah be praised with an abundant beautiful blessed praise, a never-ending praise, a praise which we will never bid farewell to and an indispensable praise, He is our Lord.’</div>",
			"Dua to Say upon Completing the Meal|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/172.gif'></div>|<div class='dua_trans'>‘All praise is for Allah who fed me this and provided it for me without any might nor power from myself.’</div>",
			"Dua to Say When Seeing the Early or Premature Fruit|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/178.gif'></div>|<div class='dua_trans'>‘O Allah, bless our fruit for us, bless our town for us, bless our saa’ for us and bless our mudd for us.’</div>",
			"Before Sleep: All Praise is for Allah Who Sheltered Us|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/104.gif'></div>|<div class='dua_trans'>‘All praise is for Allah, Who fed us and gave us drink, and Who is sufficient for us and has sheltered us, for how many have none to suffice them or shelter them.’</div>",
			"Dua to Say After Leaving the Toilet|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/011.gif'></div>|<div class='dua_trans'>‘I ask You (Allah) for forgiveness.’</div>",
			"Dua to Say Before Entering Toilet|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/010.gif'></div>|<div class='dua_trans'>[In the name of Allaah]. O Allaah, I take refuge with you from all evil and evil-doers.</div>",
			"Dua to Say When Visiting a Sick Person|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/140.gif'></div>|<div>‘Any Muslim servant who visits a sick person whose prescribed moment of death has not arrived and supplicates seven times:</div><div class='dua_trans'>‘I ask Allah The Supreme, Lord of the magnificent throne to cure you’.</div><div>He (the sick person) will be cured.’</div>",
			"Dua to Say When Visiting a Sick Person|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/139.gif'></div>|<div>When the Prophet (PBUH) would enter upon a sick person, he would say:</div><div class='dua_trans'>‘Never mind, may it (the sickness) be a purification, if Allah wills.’</div>",
			"Dua to Say When Feeling Pain Somewhere in the Body|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/231.gif'></div>|<div>‘Place your hand at the site of the pain and say:</div><div>(1)</div><div class='dua_trans'>‘In the name of Allah’ (three times)<br />…then supplicate seven times:</div><div>(2)</div><div class='dua_trans'>‘I take refuge with Allah and within His omnipotence from the evil that I feel and am wary of.’</div>",
			"Dua for the One Who Has Offered You Some of His Wealth|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/192.gif'></div>|<div class='dua_trans'>‘May Allah bless for you, your family and wealth.’</div>",
			"Dua to Say After a Rainfall|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/165.gif'></div>|<div class='dua_trans'>‘We have been given rain by the grace and mercy of Allah.’</div>",
			"Dua to Say During a Wind Storm|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/159.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You for it’s goodness, the good within it, and the good it was sent with, and I take refuge with You from it’s evil, the evil within it, and from the evil it was sent with.’</div>",
			"Dua to Say During a Wind Storm|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/158.gif'></div>|<div class='dua_trans'>‘O Allah, I ask You for it’s goodness and I take refuge with You from it’s evil.’</div>",
			"Dua to Say upon Sighting the Crescent Moon|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/167.gif'></div>|<div class='dua_trans'>‘Allah is the greatest. O Allah, let the crescent loom above us in safety, faith, peace, and Islaam, and in agreement with all that You love and pleases You. Our Lord and your Lord is Allah.’</div>",
			"Dua to Say When Asking Allah for Clear Skies|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/166.gif'></div>|<div class='dua_trans'>‘O Allah, let the rain fall around us and not upon us, O Allah, (let it fall) on the pasture, hills, valleys and roots of trees.’</div>",
			"Dua to Say When Asking Allah for Rain|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/163.gif'></div>|<div class='dua_trans'>‘O Allah, provide water for Your servants and Your cattle, spread out Your mercy and resurrect Your dead land.’</div>",
			"Dua to Say When Asking Allah for Rain|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/162.gif'></div>|<div class='dua_trans'>‘O Allah, relieve us, O Allah, relieve us, O Allah, relieve us.’</div>",
			"Dua to Say When Asking Allah for Rain|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/161.gif'></div>|<div class='dua_trans'>‘O Allah, send upon us helpful, wholesome and healthy rain, beneficial not harmful rain, now, not later.’</div>",
			"Dua to Say When it Rains|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/164.gif'></div>|<div class='dua_trans'>‘O Allah, may it be a beneficial rain cloud.’</div>",
			"Dua to Say upon Hearing Thunder|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/160.gif'></div>|<div>When ‘Abdullaah Ibn Az-Zubayr used to hear thunder he would stop talking and say:</div><div class='dua_trans'>‘How perfect He is, (The One) Whom the thunder declares His perfection with His praise, as do the angels out of fear of Him.’</div>",
			"Dua of the Resident for The Traveler|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/204.gif'></div>|<div class='dua_trans'>‘May Allah endow you with taqwaa forgive your sins and facilitate all good for you, wherever you be.’</div>",
			"Dua of the Resident for the Traveler|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/203.gif'></div>|<div class='dua_trans'>‘I place your religion, your faithfulness and the ends of your deeds in the trust of Allah.’</div>",
			"Dua of the Traveler for the Resident|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/202.gif'></div>|<div class='dua_trans'>‘I place you in the trust of Allah, whose trust is never misplaced.’</div>",
			"Dua to Say When Stopping or Lodging Somewhere While Traveling|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/207.gif'></div>|<div class='dua_trans'>‘I take refuge in Allah’s perfect words from the evil that He has created.’</div>",
			"Dua to Say While Returning From Travel|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/208.gif'></div>|<div>‘Ibn ‘Umar (RA) reported that the Messenger of Allah (PBUH), on return from a battle or from performing the pilgrimage, would say at every high point:</div><div>(1)</div><div class='dua_trans'>‘Allah is the greatest, Allah is the greatest, Allah is the greatest.’</div><div>Then he would say:</div><div>(2)</div><div class='dua_trans'>‘None has the right to be worshipped except Allah, alone, without partner. To Him belongs all sovereignty and praise, and He is over all things omnipotent. We return, repent, worship and praise our Lord. Allah fulfilled His promise, aided His Servant, and single-handedly defeated the allies.’</div>",
			"Dua of the Traveler as Dawn Approaches|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/206.gif'></div>|<div class='dua_trans'>‘May a witness, be witness to our praise of Allah for His favours and bounties upon us. Our Lord, protect us, show favour on us and deliver us from every evil. I take refuge in Allah from the fire.’</div>",
			"Dua for the Deceased at the Funeral Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/150.gif'></div>|<div class='dua_trans'>‘O Allah, so-and-so is under Your care and protection so protect him from the trial of the grave and torment of the Fire. Indeed You are faithful and truthful. Forgive and have mercy upon him, surely You are The Oft-Forgiving, The Most-Merciful’.</div>",
			"Dua of Condolence|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/154.gif'></div>|<div>(1)</div><div class='dua_trans'>‘Verily to Allah, belongs what He took and to Him belongs what He gave, and everything with Him has an appointed time..and then he ordered for her to be patient and hope for Allah’s reward.’</div><div>And one can also say:</div><div>(2)</div><div class='dua_trans'>‘May Allah magnify your reward, make better your solace and forgive your deceased.’</div>",
			"Dua for the Sick Person Who has Renounced All Hope of Life|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/144.gif'></div>|<div class='dua_trans'>‘None has the right to be worshipped except Allah and Allah is the greatest. None has the right to be worshipped except Allah, alone. None has the right to be worshipped except Allah, alone, without partner. None has the right to be worshipped except Allah, to Him belongs all sovereignty and praise. None has the right to be worshipped except Allah and there is no might and no power except with Allah.’</div>",
			"Dua for the Sick Person Who has Renounced All Hope of Life|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/143.gif'></div>|<div>Aisha (RA) related that the Prophet (S) (during his illness in which he passed away) would dip his hands in water and then he would wipe his face and say:</div><div class='dua_trans'>‘None has the right to be worshipped except Allah, death does indeed contain agony.’</div>",
			"Dua for the Sick Person Who has Renounced All Hope of Life|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/142.gif'></div>|<div class='dua_trans'>‘O Allah, forgive me, have mercy upon me and unite me with the highest companions.’</div>",
			"Dua to Say When Closing the Eyes of the Deceased|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/147.gif'></div>|<div class='dua_trans'>‘O Allah, forgive – here the name of the deceased is mentioned – and raise his rank among the rightly guided, and be a successor to whom he has left behind, and forgive us and him O Lord of the worlds. Make spacious his grave and illuminate it for him.’</div>",
			"Dua to Say When Placing the Deceased in the Grave|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/155.gif'></div>|<div class='dua_trans'>‘In the name of Allah and upon the sunnah of the Messenger of Allah.’</div>",
			"Dua to Say When Visiting Graves|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/157.gif'></div>|<div class='dua_trans'>‘Peace be upon you all, O inhabitants of the graves, amongst the believers and the Muslims. Verily we will, Allah willing, be united with you, we ask Allah for well-being for us and you.’</div>",
			"Instruction for the One Nearing Death|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/145.gif'></div>|<div>‘He whose last words are (the following) will enter paradise:’</div><div class='dua_trans'>‘None has the right to be worshiped except Allah.’</div>",
			"Before Sleep: In Your Name My Lord, I Lie Down and in Your Name I Rise|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/098.gif'></div>|<div>‘If one of you rises from his bed and then returns to it he should dust it with the edge of his garment three times for he does not know what has occurred in his absence and when he lies down he should supplicate:</div><div class='dua_trans'>‘In Your name my Lord, I lie down and I in Your name I rise, so if You should take my soul then have mercy upon it, and if You should return my soul then protect it in the manner You do so with Your righteous servants.’</div>",
			"Before Sleep: In Your Name O Allah, I Live and Die|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/101.gif'></div>|<div class='dua_trans'>‘In Your name O Allah, I live and die.’</div>",
			"Before Sleep: O Allah, Protect Me from Your Punishment|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/100.gif'></div>|<div>The Prophet (PBUH) would place his right hand under his cheek when about to sleep and supplicate (3 times):</div><div class='dua_trans'>‘O Allah, protect me from Your punishment on the day Your servants are resurrected.’</div>",
			"Before Sleep: O Allah, Verily You Have Created My Soul|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/099.gif'></div>|<div class='dua_trans'>‘O Allah, verily You have created my soul and You shall take it’s life, to You belongs it’s life and death. If You should keep my soul alive then protect it, and if You should take its life then forgive it. O Allah, I ask You to grant me good health.’</div>",
			"Before Sleep: Reciting 2 Chapters from Qur&#039;an|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/106.gif'></div>|<div>‘The Prophet (PBUH) never used to sleep until he had recited Surah As-Sajdah and Surah Al-Mulk.’</div>",
			"Before Sleep: Reciting Ayat Al-Kursi|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/096.gif'></div>|<div>The Prophet (PBUH) also said: ‘When you are about to sleep recite aayat-ul-kursiyy till the end of the verse for there will remain over you a protection from Allah and no devil will draw near to you until morning.’</div><div class='dua_trans'>‘None has the right to be worshipped but He, the Ever Living, the One Who sustains and protects all that exists. Neither slumber, nor sleep overtake Him. To Him belongs whatever is in the heavens and whatever is on earth. Who is he that can intercede with Him except with His Permission? He knows what happens to them (His creatures) in this world, and what will happen to them in the Hereafter . And they will never compass anything of His Knowledge except that which He wills. His Kursî[] extends over the heavens and the earth, and He feels no fatigue in guarding and preserving them. And He is the Most High, the Most Great‘.</div>",
			"Before Sleep: Saying Subhanallah, Alhamdulillah, Allahu Akbar|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/102.gif'></div>|<div>The prophet Muhammad (PBUH) said to Ali (RA) and Fatima (RA):<br />‘Shall I not direct you both to something better than a servant? When you go to bed say (the following) for that is indeed better for you both than a servant.’:</div><div class='dua_trans'>‘How Perfect Allah is.’</div><div>(33 times)</div><div class='dua_trans'>‘All praise is for Allah.’</div><div>(33 times)</div><div class='dua_trans'>‘Allah is the greatest.’</div><div>(34 times)</div>",
			"Waking Up: All Praise is for Allah Who Gave Us Life|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/001.gif'></div>|<div class='dua_trans'>All praise is for Allah who gave us life after having taken it from us and unto Him is the Resurrection.</div>",
			"Waking Up: All Praise is for Allah Who Returned My Soul|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/003.gif'></div>|<div class='dua_trans'>All praise is for Allah who restored to me my health and returned my soul and has allowed me to remember Him.</div>",
			"Dua for the Deceased at the Funeral Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/151.gif'></div>|<div class='dua_trans'>‘O Allah, Your servant and the son of Your maidservant is in need of Your mercy and You are without need of his punishment. If he was righteous then increase his reward and if he was wicked then look over his sins.’</div>",
			"Dua for the Deceased Child at the Funeral Prayer|<div class='dua_image'><img src='/wp-content/plugins/azkaar-english/dua-arabic-images/153.gif'></div>|<div class='dua_trans'>‘O Allah, make him a preceding reward, a prepayment and a recompense for us.’</div>"
		);

		$random_element = rand(0, sizeof($azkaar_array)-1);
		$element_values = explode("|", $azkaar_array[$random_element]);

		if (isset($element_values[0]) && isset($element_values[1]) && isset($element_values[2])) {
			$widget_data .= "<h2>" . $element_values[0] . "</h2>";
			$widget_data .= $element_values[1];
			$widget_data .= "<div>" . $element_values[2] . "</div>";
			$widget_data .= "<div class='azkaar_link'><a target='_blank' href='http://www.azkaar.com/english'>azkaar.com</a></div>";
		} else {
			return;
		}
		
		$widget_data .= '';

		$widget_data = '<div id="azkaar-english-widget">'.$widget_data.'</div>';
		
		echo $before_widget . $widget_data . $after_widget;
		
				
	} // widget function
		
	
	
}


// register widget
function azkaar_english_register_widget() {
	register_widget( 'AzkaarEnglishPluginWidget' );
}
add_action( 'widgets_init', 'azkaar_english_register_widget' );


?>